[package]
name = "montgomery_reduction"
version = "0.1.0"
edition = "2021"


[profile.release]
debug = 2
lto = true

[profile.bench]
lto = true

[[bin]]
name = "inst"
path = "./src/inst.rs"

[[bin]]
name = "em"
path = "./src/emmart.rs"

[dependencies]
libc = "0.2.169"
num-modular = "0.6.1"
num-traits = "0.2.19"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

[dev-dependencies]
criterion = "0.5"
rand = "0.8"

[[bench]]
name = "montgomery"
harness = false
